### PR TITLE
Job history stats with start time, duration, arguments, status, and exception

### PR DESCRIPTION
**Pull request by emilong**
We wanted to be able to drill down into the history for certain jobs if their stats looked unusual. This commit adds argument, timing, and result tracking to the last few (default 100) jobs and a web view to resque-web.

### CODE REVIEW

**Comment by lukeasrodgers** [comment]
@emilong I know it's been a long time -- I recently started helping the maintainer with this repo, and I'd like to merge this PR, but it needs a couple changes:

* rebase off master to fix merge conflicts, and so that CI will run
* the history is a bit messed up -- the first two commits are duplicates of each other except for the change to the `VERSION` file (which I assume was a mistake)
* ideally all commits would be squashed down into one, as they represent a single logical feature/change

If you are interested/able to do this, go for it and I will merge (assuming tests pass). If you aren't interested or don't have the time, let me know, and I'll make these changes (your name will still be on the commit).
thanks

**Comment by emilong** [comment]
Hi @lukeasrodgers! Wow, I do not even remember working on this, but thank you for taking over the project. I'm not even working in Ruby much these days, so it would probably be best for you or someone else to work on the merge for quality's sake :smile:. No worries about keeping my name on it if you do, I'd just be happy to be helpful!

**Comment by lukeasrodgers** [comment]
@emilong sounds good, thanks.

Recently I discovered you can see all your old (and still-open) PRs by going to https://github.com/pulls -- can be an interesting blast from the past :)

**Comment by lukeasrodgers** [comment]
Superseded by #24

**Pull request closed without merging**
